import type { HistoricalCampaignPattern } from "@/lib/types/domain";

export const historicalCampaignLibrary: HistoricalCampaignPattern[] = [
  {
    id: "desert-storm",
    label: "Desert Shield / Desert Storm",
    theater: "Gulf",
    periodLabel: "1990-1991",
    doctrineNotes: [
      "Classic shaping-to-decisive-operation sequence with heavy air-refueling and command-and-control buildup.",
      "Termination followed battlefield success but still required force-protection and orderly redeployment.",
    ],
    phases: [
      {
        phaseId: "desert-shield-buildup",
        label: "Strategic buildup",
        actionType: "initiation",
        cadence: "weekly",
        dateStart: "1990-08-07",
        dateEnd: "1991-01-16",
        politicalTrigger: "Iraq invades Kuwait; coalition force buildup begins.",
        forceBuildupIndicators: ["air bridge density", "tanker sortie tempo", "carrier posture"],
        strikeInitiationIndicators: [],
        sustainmentIndicators: ["military cargo arrivals", "ISR persistence"],
        settlementSignals: ["UN deadline diplomacy"],
        terminationLanguageTiming: "Not present during buildup.",
        logisticsDrawdownSignals: [],
        retrogradeSignals: [],
        residualOverwatchSignals: ["carrier and air defense coverage retained"],
      },
      {
        phaseId: "desert-storm-air-campaign",
        label: "Air campaign sustainment",
        actionType: "sustainment",
        cadence: "weekly",
        dateStart: "1991-01-17",
        dateEnd: "1991-02-23",
        politicalTrigger: "Coalition air campaign begins.",
        forceBuildupIndicators: ["command-aircraft movement", "force movement score"],
        strikeInitiationIndicators: ["strike-package tempo", "cross-border strike indicator"],
        sustainmentIndicators: ["tanker sortie tempo", "support-vessel density", "ISR persistence"],
        settlementSignals: [],
        terminationLanguageTiming: "Followed battlefield objectives rather than preceding them.",
        logisticsDrawdownSignals: [],
        retrogradeSignals: [],
        residualOverwatchSignals: ["high force protection"],
      },
      {
        phaseId: "desert-storm-redeployment",
        label: "Redeployment with cover",
        actionType: "retrograde_with_cover",
        cadence: "weekly",
        dateStart: "1991-02-24",
        dateEnd: "1991-04-30",
        politicalTrigger: "Ceasefire conditions and end of large-scale combat.",
        forceBuildupIndicators: [],
        strikeInitiationIndicators: [],
        sustainmentIndicators: ["residual overwatch", "force protection"],
        settlementSignals: ["ceasefire diplomacy"],
        terminationLanguageTiming: "Political termination lagged real retrograde mechanics.",
        logisticsDrawdownSignals: ["reduced tanker support", "shrinking air bridge"],
        retrogradeSignals: ["equipment withdrawal", "base turnover"],
        residualOverwatchSignals: ["continued patrol and deterrent posture"],
      },
    ],
  },
  {
    id: "allied-force",
    label: "Kosovo / Allied Force",
    theater: "Balkans",
    periodLabel: "1999",
    doctrineNotes: [
      "Coercive air campaign with diplomacy and force pressure running in parallel.",
      "Operational pauses and settlement pressure can coexist with sustained ISR and command coverage.",
    ],
    phases: [
      {
        phaseId: "allied-force-escalation",
        label: "Escalatory air pressure",
        actionType: "escalation",
        cadence: "weekly",
        dateStart: "1999-03-24",
        dateEnd: "1999-05-31",
        politicalTrigger: "NATO initiates air operations against FRY targets.",
        forceBuildupIndicators: ["carrier posture", "tanker tempo", "ISR persistence"],
        strikeInitiationIndicators: ["strike-package tempo", "retaliation-threat language"],
        sustainmentIndicators: ["air bridge density"],
        settlementSignals: ["intermittent diplomacy"],
        terminationLanguageTiming: "Negotiation signals rose before formal termination was secure.",
        logisticsDrawdownSignals: [],
        retrogradeSignals: [],
        residualOverwatchSignals: ["persistent ISR", "command aircraft"],
      },
      {
        phaseId: "allied-force-settlement",
        label: "Coercive settlement",
        actionType: "coercive_settlement",
        cadence: "weekly",
        dateStart: "1999-06-01",
        dateEnd: "1999-06-20",
        politicalTrigger: "Belgrade accepts terms under pressure.",
        forceBuildupIndicators: [],
        strikeInitiationIndicators: ["tempo still available as leverage"],
        sustainmentIndicators: ["coverage retained until compliance"],
        settlementSignals: ["official meetings", "mediator activity", "ceasefire references"],
        terminationLanguageTiming: "Settlement language strengthened before full operational release.",
        logisticsDrawdownSignals: ["beginning drawdown"],
        retrogradeSignals: ["selective redeployment"],
        residualOverwatchSignals: ["continued alliance coverage"],
      },
    ],
  },
  {
    id: "iraq-drawdown",
    label: "Iraq drawdown / New Dawn",
    theater: "Iraq",
    periodLabel: "2010-2011",
    doctrineNotes: [
      "U.S. drawdown preserved advisory, overwatch, and force-protection elements late into the transition.",
      "Withdrawal is not synonymous with immediate termination of military risk posture.",
    ],
    phases: [
      {
        phaseId: "iraq-pause-transition",
        label: "Transition and pause",
        actionType: "operational_pause",
        cadence: "monthly",
        dateStart: "2010-08-01",
        dateEnd: "2011-06-30",
        politicalTrigger: "Mission transition from combat to advise-and-assist.",
        forceBuildupIndicators: [],
        strikeInitiationIndicators: ["reduced strike tempo"],
        sustainmentIndicators: ["logistics still elevated", "residual force protection"],
        settlementSignals: ["political negotiation over status"],
        terminationLanguageTiming: "Mission language moved faster than full physical retrograde.",
        logisticsDrawdownSignals: ["gradual air bridge decline"],
        retrogradeSignals: ["base closures begin"],
        residualOverwatchSignals: ["protective overwatch", "advisory presence"],
      },
      {
        phaseId: "iraq-retrograde",
        label: "Retrograde with cover",
        actionType: "retrograde_with_cover",
        cadence: "monthly",
        dateStart: "2011-07-01",
        dateEnd: "2011-12-31",
        politicalTrigger: "Final withdrawal planning becomes binding.",
        forceBuildupIndicators: [],
        strikeInitiationIndicators: [],
        sustainmentIndicators: ["convoy protection", "residual overwatch"],
        settlementSignals: ["official end-state coordination"],
        terminationLanguageTiming: "Formal end-state coincided with but did not fully explain retrograde mechanics.",
        logisticsDrawdownSignals: ["shrinking cargo bridge", "equipment disposition"],
        retrogradeSignals: ["base turnover", "route security", "final convoy movement"],
        residualOverwatchSignals: ["continued protective posture until exit"],
      },
    ],
  },
  {
    id: "afghanistan-retrograde",
    label: "Afghanistan retrograde",
    theater: "Afghanistan",
    periodLabel: "2021",
    doctrineNotes: [
      "Retrograde can intensify logistics even as strike tempo declines.",
      "Residual overwatch and evacuation protection can coexist with public end-language and shrinking battlefield activity.",
    ],
    phases: [
      {
        phaseId: "afghanistan-retrograde",
        label: "Retrograde with overwatch",
        actionType: "retrograde_with_cover",
        cadence: "weekly",
        dateStart: "2021-05-01",
        dateEnd: "2021-08-15",
        politicalTrigger: "Withdrawal order and base closure sequence.",
        forceBuildupIndicators: [],
        strikeInitiationIndicators: ["selective defensive strikes only"],
        sustainmentIndicators: ["air bridge density", "military cargo arrivals", "ISR persistence"],
        settlementSignals: ["political talks but deteriorating battlefield context"],
        terminationLanguageTiming: "Public withdrawal framing preceded complete stabilization.",
        logisticsDrawdownSignals: ["base handover", "equipment removal"],
        retrogradeSignals: ["cargo surges", "evacuation logistics", "base closure"],
        residualOverwatchSignals: ["force protection", "evacuation cover", "ISR"],
      },
      {
        phaseId: "afghanistan-withdrawal-without-termination",
        label: "Withdrawal without genuine termination",
        actionType: "withdrawal_without_termination",
        cadence: "weekly",
        dateStart: "2021-08-16",
        dateEnd: "2021-08-31",
        politicalTrigger: "Collapse forces emergency exit under protective cover.",
        forceBuildupIndicators: [],
        strikeInitiationIndicators: ["defensive response strikes"],
        sustainmentIndicators: ["extreme air bridge"],
        settlementSignals: [],
        terminationLanguageTiming: "End-state language and actual strategic stability were misaligned.",
        logisticsDrawdownSignals: ["final exit"],
        retrogradeSignals: ["emergency extraction"],
        residualOverwatchSignals: ["high protective posture to the end"],
      },
    ],
  },
];
